version: '2'

services:
  redis:
    image: redis

  db:
    image: postgres:9.6
    environment:
      POSTGRES_DB: process.env.PGDATABASE
      POSTGRES_USER: process.env.PGUSER
      POSTGRES_PASSWORD: process.env.PGPASSWORD
    ports:
      - '5432:5432'

  app:
    build: .
    depends_on:
      - db
      - redis
    ports:
      - '5555:5555'
    volumes:
      - .:/usr/src/app
      # prevents host/container contamination
      - /usr/src/app/node_modules
    env_file: .env
    environment:
      DATABASE_URL: process.env.PGHOST
      NODE_ENV: development
      REDIS_HOST: redis://redis:6379
    links:
      - 'redis'
    command: npm run dev
